#%RAML 1.0 DataType
displayName: order
description: Defines the data type in order-api RAML

type: object
properties:
  id?: string
  name: string
  category: string
  color: string
  size: string
  price: string
  instock: string
  returnable: boolean

